-- Banco de dados
CREATE DATABASE IF NOT EXISTS Flintstones
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_general_ci;

USE Flintstones;


--  Tabela de arquivos de mídia
CREATE TABLE IF NOT EXISTS media_files (
    id INT AUTO_INCREMENT PRIMARY KEY,
    file_name VARCHAR(255) NOT NULL,
    file_url TEXT NOT NULL,
    file_type ENUM('gif', 'image', 'video', 'audio') NOT NULL,
    category VARCHAR(100) NOT NULL,
    tags VARCHAR(255),
    description TEXT, -- 🔹 coluna que faltava
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


--  Tabela de uso da mídia
CREATE TABLE IF NOT EXISTS media_usage (
    id INT AUTO_INCREMENT PRIMARY KEY,
    media_id INT NOT NULL,
    command_name VARCHAR(50) NOT NULL,
    usage_count INT DEFAULT 1,
    last_used TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (media_id) REFERENCES media_files(id) ON DELETE CASCADE,
    UNIQUE KEY uniq_media_command (media_id, command_name) -- 🔑 Necessário para ON DUPLICATE KEY
);

-- 👤 Preferências do usuário
CREATE TABLE IF NOT EXISTS user_preferences (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id VARCHAR(50) NOT NULL,
    preference_key VARCHAR(50) NOT NULL,
    preference_value VARCHAR(255),
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_user_pref (user_id, preference_key)
);


 
INSERT INTO media_files (file_name, file_url, file_type, category, tags, description)
VALUES
('Build_Aatrox', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753871214/Screenshot_from_2025-07-30_03-55-26_iuxcxb.png', 'image', 'build', 'Aatrox, build, League of Legends', 'Imagem de build atual de Aatrox, campeão do League of Legends'),
('Build_Ahri', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753871894/Screenshot_from_2025-07-30_04-16-44_xepazo.png', 'image', 'build', 'Ahri, build, League of Legends', 'Imagem de build atual de Ahri, campeão do League of Legends'),
('Build_Akali', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753871923/Screenshot_from_2025-07-30_04-17-11_pkkxab.png', 'image', 'build', 'Akali, build, League of Legends', 'Imagem de build atual de Akali, campeão do League of Legends'),
('Build_Akshan', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753871963/Screenshot_from_2025-07-30_04-17-48_n3frn2.png', 'image', 'build', 'Akshan, build, League of Legends', 'Imagem de build atual de Akshan, campeão do League of Legends'),
('Build_Alistar', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753871994/Screenshot_from_2025-07-30_04-18-23_gvpotx.png', 'image', 'build', 'Alistar, build, League of Legends', 'Imagem de build atual de Alistar, campeão do League of Legends'),
('Build_Ambessa', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877828/Screenshot_from_2025-07-30_05-52-08_ypaegq.png', 'image', 'build', 'Ambessa, build, League of Legends', 'Imagem de build atual de Ambessa, campeão do League of Legends'),
('Build_Amumu', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753872026/Screenshot_from_2025-07-30_04-18-54_wt9rvl.png', 'image', 'build', 'Amumu, build, League of Legends', 'Imagem de build atual de Amumu, campeão do League of Legends'),
('Build_Anivia', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753872057/Screenshot_from_2025-07-30_04-19-25_dmxcis.png', 'image', 'build', 'Anivia, build, League of Legends', 'Imagem de build atual de Anivia, campea o do League of Legends'),
('Build_Annie', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753872086/Screenshot_from_2025-07-30_04-19-56_nkqxi3.png', 'image', 'build', 'Annie, build, League of Legends', 'Imagem de build atual de Annie, campeão do League of Legends'),
('Build_Aphelios', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753872116/Screenshot_from_2025-07-30_04-20-27_loe1q7.png', 'image', 'build', 'Aphelios, build, League of Legends', 'Imagem de build atual de Aphelios, campeão do League of Legends'),
('Build_Ashe', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753872152/Screenshot_from_2025-07-30_04-20-59_hmqlhq.png', 'image', 'build', 'Ashe, build, League of Legends', 'Imagem de build atual de Ashe, campeão do League of Legends'),
('Build_Aurelion_Sol', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875060/Screenshot_from_2025-07-30_04-27-50_dwpaav.png', 'image', 'build', 'Aurelion Sol, build, League of Legends', 'Imagem de build atual de Aurelion Sol, campeão do League of Legends'),
('Build_Azir', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875060/Screenshot_from_2025-07-30_04-28-20_npppta.png', 'image', 'build', 'Azir, build, League of Legends', 'Imagem de build atual de Azir, campeão do League of Legends'),
('Build_Bard', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875061/Screenshot_from_2025-07-30_04-28-41_iczhor.png', 'image', 'build', 'Bard, build, League of Legends', 'Imagem de build atual de Bard, campeão do League of Legends'),
('Build_BelVeth', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875061/Screenshot_from_2025-07-30_04-29-01_kcggtb.png', 'image', 'build', 'BelVeth, build, League of Legends', 'Imagem de build atual de BelVeth, campeão do League of Legends'),
('Build_Blitzcrank', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875061/Screenshot_from_2025-07-30_04-29-29_sgp8ys.png', 'image', 'build', 'Blitzcrank, build, League of Legends', 'Imagem de build atual de Blitzcrank, campeão do League of Legends'),
('Build_Brand', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875065/Screenshot_from_2025-07-30_04-29-46_a5nay0.png', 'image', 'build', 'Brand, build, League of Legends', 'Imagem de build atual de Brand, campeão do League of Legends'),
('Build_Braum', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875066/Screenshot_from_2025-07-30_04-30-01_srosrp.png', 'image', 'build', 'Braum, build, League of Legends', 'Imagem de build atual de Braum, campeão do League of Legends'),
('Build_Briar', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753873135/Screenshot_from_2025-07-30_04-37-41_s7wbi5.png', 'image', 'build', 'Briar, build, League of Legends', 'Imagem de build atual de Briar, campeão do League of Legends'),
('Build_Caitlyn', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875067/Screenshot_from_2025-07-30_04-30-18_i9cfir.png', 'image', 'build', 'Caitlyn, build, League of Legends', 'Imagem de build atual de Caitlyn, campeão do League of Legends'),
('Build_Camille', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875067/Screenshot_from_2025-07-30_04-30-37_yri2th.png', 'image', 'build', 'Camille, build, League of Legends', 'Imagem de build atual de Camille, campeão do League of Legends'),
('Build_Cassiopeia', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875068/Screenshot_from_2025-07-30_04-30-57_peoiyr.png', 'image', 'build', 'Cassiopeia, build, League of Legends', 'Imagem de build atual de Cassiopeia, campeão do League of Legends'),
('Build_ChoGath', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875071/Screenshot_from_2025-07-30_04-31-15_qwwoqn.png', 'image', 'build', 'ChoGath, build, League of Legends', 'Imagem de build atual de ChoGath, campeão do League of Legends'),
('Build_Corki', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875071/Screenshot_from_2025-07-30_04-31-31_x47tji.png', 'image', 'build', 'Corki, build, League of Legends', 'Imagem de build atual de Corki, campeão do League of Legends'),
('Build_Darius', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875072/Screenshot_from_2025-07-30_04-31-51_ak71pl.png', 'image', 'build', 'Darius, build, League of Legends', 'Imagem de build atual de Darius, campeão do League of Legends'),
('Build_Diana', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875072/Screenshot_from_2025-07-30_04-32-30_i1qswe.png', 'image', 'build', 'Diana, build, League of Legends', 'Imagem de build atual de Diana, campeão do League of Legends'),
('Build_Draven', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875073/Screenshot_from_2025-07-30_04-32-46_rrb1zv.png', 'image', 'build', 'Draven, build, League of Legends', 'Imagem de build atual de Draven, campeão do League of Legends'),
('Build_Dr_Mundo', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875075/Screenshot_from_2025-07-30_04-32-57_ptz6oh.png', 'image', 'build', 'Dr Mundo, build, League of Legends', 'Imagem de build atual de Dr Mundo, campeão do League of Legends'),
('Build_Ekko', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875080/Screenshot_from_2025-07-30_04-33-30_vfxkfd.png', 'image', 'build', 'Ekko, build, League of Legends', 'Imagem de build atual de Ekko, campeão do League of Legends'),
('Build_Elise', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875081/Screenshot_from_2025-07-30_04-33-45_qo8d2m.png', 'image', 'build', 'Elise, build, League of Legends', 'Imagem de build atual de Elise, campea o do League of Legends'),
('Build_Evelynn', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875082/Screenshot_from_2025-07-30_04-34-05_dyehzd.png', 'image', 'build', 'Evelynn, build, League of Legends', 'Imagem de build atual de Evelynn, campeão do League of Legends'),
('Build_Ezreal', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875083/Screenshot_from_2025-07-30_04-34-24_f3bofg.png', 'image', 'build', 'Ezreal, build, League of Legends', 'Imagem de build atual de Ezreal, campeão do League of Legends'),
('Build_Fiddlesticks', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875084/Screenshot_from_2025-07-30_04-34-46_km2pph.png', 'image', 'build', 'Fiddlesticks, build, League of Legends', 'Imagem de build atual de Fiddlesticks, campeão do League of Legends'),
('Build_Fiora', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875085/Screenshot_from_2025-07-30_04-35-04_cfn4f1.png', 'image', 'build', 'Fiora, build, League of Legends', 'Imagem de build atual de Fiora, campeão do League of Legends'),
('Build_Fizz', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875086/Screenshot_from_2025-07-30_04-35-25_uozzgr.png', 'image', 'build', 'Fizz, build, League of Legends', 'Imagem de build atual de Fizz, campeão do League of Legends'),
('Build_Galio', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875087/Screenshot_from_2025-07-30_04-35-44_kdvvem.png', 'image', 'build', 'Galio, build, League of Legends', 'Imagem de build atual de Galio, campeão do League of Legends'),
('Build_Gangplank', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875088/Screenshot_from_2025-07-30_04-36-06_mwnk7y.png', 'image', 'build', 'Gangplank, build, League of Legends', 'Imagem de build atual de Gangplank, campeão do League of Legends'),
('Build_Garen', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875089/Screenshot_from_2025-07-30_04-36-22_cbxdnv.png', 'image', 'build', 'Garen, build, League of Legends', 'Imagem de build atual de Garen, campeão do League of Legends'),
('Build_Gnar', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875090/Screenshot_from_2025-07-30_04-36-44_zvhca6.png', 'image', 'build', 'Gnar, build, League of Legends', 'Imagem de build atual de Gnar, campeão do League of Legends'),
('Build_Gragas', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875090/Screenshot_from_2025-07-30_04-37-06_cbkprb.png', 'image', 'build', 'Gragas, build, League of Legends', 'Imagem de build atual de Gragas, campeão do League of Legends'),
('Build_Graves', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875091/Screenshot_from_2025-07-30_04-37-26_cj5sol.png', 'image', 'build', 'Graves, build, League of Legends', 'Imagem de build atual de Graves, campeão do League of Legends'),
('Build_Gwen', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875091/Screenshot_from_2025-07-30_04-37-46_c3ffhf.png', 'image', 'build', 'Gwen, build, League of Legends', 'Imagem de build atual de Gwen, campeão do League of Legends'),
('Build_Hecarim', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875092/Screenshot_from_2025-07-30_04-38-07_u1tz9y.png', 'image', 'build', 'Hecarim, build, League of Legends', 'Imagem de build atual de Hecarim, campeão do League of Legends'),
('Build_Heimerdinger', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875092/Screenshot_from_2025-07-30_04-45-11_pndkka.png', 'image', 'build', 'Heimerdinger, build, League of Legends', 'Imagem de build atual de Heimerdinger, campeão do League of Legends'),
('Build_Hwei', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877834/Screenshot_from_2025-07-30_05-53-13_hbti7x.png', 'image', 'build', 'Hwei, build, League of Legends', 'Imagem de build atual de Hwei, campeão do League of Legends'),
('Build_Illaoi', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875093/Screenshot_from_2025-07-30_04-38-28_kojh6k.png', 'image', 'build', 'Illaoi, build, League of Legends', 'Imagem de build atual de Illaoi, campeão do League of Legends'),
('Build_Irelia', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875093/Screenshot_from_2025-07-30_04-38-48_wbq5d7.png', 'image', 'build', 'Irelia, build, League of Legends', 'Imagem de build atual de Irelia, campeão do League of Legends'),
('Build_Ivern', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875094/Screenshot_from_2025-07-30_04-39-09_piybcw.png', 'image', 'build', 'Ivern, build, League of Legends', 'Imagem de build atual de Ivern, campeão do League of Legends'),
('Build_Janna', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875094/Screenshot_from_2025-07-30_04-39-29_e5eezw.png', 'image', 'build', 'Janna, build, League of Legends', 'Imagem de build atual de Janna, campeão do League of Legends'),
('Build_Jarvan', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875095/Screenshot_from_2025-07-30_04-39-49_k0kgue.png', 'image', 'build', 'Jarvan, build, League of Legends', 'Imagem de build atual de Jarvan, campeão do League of Legends'),
('Build_Jax', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875095/Screenshot_from_2025-07-30_04-40-10_f0x43a.png', 'image', 'build', 'Jax, build, League of Legends', 'Imagem de build atual de Jax, campeão do League of Legends'),
('Build_Jayce', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875096/Screenshot_from_2025-07-30_04-40-29_qbqcuo.png', 'image', 'build', 'Jayce, build, League of Legends', 'Imagem de build atual de Jayce, campeão do League of Legends'),
('Build_Jhin', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875096/Screenshot_from_2025-07-30_04-40-50_xljbgh.png', 'image', 'build', 'Jhin, build, League of Legends', 'Imagem de build atual de Jhin, campeão do League of Legends'),
('Build_Jinx', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875102/Screenshot_from_2025-07-30_04-48-16_xgdfly.png', 'image', 'build', 'Jinx, build, League of Legends', 'Imagem de build atual de Jinx, campeão do League of Legends'),
('Build_Ksante', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875102/Screenshot_from_2025-07-30_04-48-31_rgo29l.png', 'image', 'build', 'Ksante, build, League of Legends', 'Imagem de build atual de Ksante, campeão do League of Legends'),
('Build_Kaisa', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875104/Screenshot_from_2025-07-30_04-48-54_bavfpe.png', 'image', 'build', 'Kaisa, build, League of Legends', 'Imagem de build atual de Kaisa, campeão do League of Legends'),
('Build_Kalista', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875106/Screenshot_from_2025-07-30_04-49-09_zyfusl.png', 'image', 'build', 'Kalista, build, League of Legends', 'Imagem de build atual de Kalista, campeão do League of Legends'),
('Build_Karma', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875107/Screenshot_from_2025-07-30_04-49-23_g7ictx.png', 'image', 'build', 'Karma, build, League of Legends', 'Imagem de build atual de Karma, campeão do League of Legends'),
('Build_Karthus', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875107/Screenshot_from_2025-07-30_04-49-42_gpxa7c.png', 'image', 'build', 'Karthus, build, League of Legends', 'Imagem de build atual de Karthus, campeão do League of Legends'),
('Build_Kassadin', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875108/Screenshot_from_2025-07-30_04-50-04_miqspv.png', 'image', 'build', 'Kassadin, build, League of Legends', 'Imagem de build atual de Kassadin, campeão do League of Legends'),
('Build_Katarina', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875111/Screenshot_from_2025-07-30_04-50-19_gvugis.png', 'image', 'build', 'Katarina, build, League of Legends', 'Imagem de build atual de Katarina, campeão do League of Legends'),
('Build_Kayle', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875111/Screenshot_from_2025-07-30_04-50-32_qctk3n.png', 'image', 'build', 'Kayle, build, League of Legends', 'Imagem de build atual de Kayle, campeão do League of Legends'),
('Build_Kayn', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875112/Screenshot_from_2025-07-30_04-50-47_dslgeh.png', 'image', 'build', 'Kayn, build, League of Legends', 'Imagem de build atual de Kayn, campeão do League of Legends'),
('Build_Kennen', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875113/Screenshot_from_2025-07-30_04-51-14_g0lkoy.png', 'image', 'build', 'Kennen, build, League of Legends', 'Imagem de build atual de Kennen, campeão do League of Legends'),
('Build_Khazix', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875116/Screenshot_from_2025-07-30_04-51-29_gjzlv2.png', 'image', 'build', 'Khazix, build, League of Legends', 'Imagem de build atual de Khazix, campeão do League of Legends'),
('Build_Kindred', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875116/Screenshot_from_2025-07-30_04-51-45_hmjgwd.png', 'image', 'build', 'Kindred, build, League of Legends', 'Imagem de build atual de Kindred, campeão do League of Legends'),
('Build_Kled', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875117/Screenshot_from_2025-07-30_04-52-05_ppx2nz.png', 'image', 'build', 'Kled, build, League of Legends', 'Imagem de build atual de Kled, campeão do League of Legends'),
('Build_KogMaw', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875118/Screenshot_from_2025-07-30_04-52-50_rzwmnw.png', 'image', 'build', 'KogMaw, build, League of Legends', 'Imagem de build atual de KogMaw, campeão do League of Legends'),
('Build_LeBlanc', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875120/Screenshot_from_2025-07-30_04-53-19_ar6jga.png', 'image', 'build', 'LeBlanc, build, League of Legends', 'Imagem de build atual de LeBlanc, campea o do League of Legends'),
('Build_Lee_Sin', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875121/Screenshot_from_2025-07-30_04-53-36_kd8s0z.png', 'image', 'build', 'Lee Sin, build, League of Legends', 'Imagem de build atual de Lee Sin, campeão do League of Legends'),
('Build_Leona', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875123/Screenshot_from_2025-07-30_04-53-52_zqqljf.png', 'image', 'build', 'Leona, build, League of Legends', 'Imagem de build atual de Leona, campeão do League of Legends'),
('Build_Lillia', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875124/Screenshot_from_2025-07-30_04-54-25_d6l5ht.png', 'image', 'build', 'Lillia, build, League of Legends', 'Imagem de build atual de Lillia, campeão do League of Legends'),
('Build_Lissandra', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875124/Screenshot_from_2025-07-30_04-54-46_sbk618.png', 'image', 'build', 'Lissandra, build, League of Legends', 'Imagem de build atual de Lissandra, campeão do League of Legends'),
('Build_Lucian', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875125/Screenshot_from_2025-07-30_04-55-03_ju3kce.png', 'image', 'build', 'Lucian, build, League of Legends', 'Imagem de build atual de Lucian, campeão do League of Legends'),
('Build_Lulu', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875128/Screenshot_from_2025-07-30_04-55-22_eupzag.png', 'image', 'build', 'Lulu, build, League of Legends', 'Imagem de build atual de Lulu, campeão do League of Legends'),
('Build_Lux', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875129/Screenshot_from_2025-07-30_04-55-36_vvcx85.png', 'image', 'build', 'Lux, build, League of Legends', 'Imagem de build atual de Lux, campeão do League of Legends'),
('Build_Malphite', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875129/Screenshot_from_2025-07-30_04-55-56_hax6mk.png', 'image', 'build', 'Malphite, build, League of Legends', 'Imagem de build atual de Malphite, campeão do League of Legends'),
('Build_Malzahar', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875130/Screenshot_from_2025-07-30_04-56-14_inhqal.png', 'image', 'build', 'Malzahar, build, League of Legends', 'Imagem de build atual de Malzahar, campeão do League of Legends'),
('Build_Maokai', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875134/Screenshot_from_2025-07-30_04-56-39_vofou0.png', 'image', 'build', 'Maokai, build, League of Legends', 'Imagem de build atual de Maokai, campeão do League of Legends'),
('Build_Master_Yi', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875134/Screenshot_from_2025-07-30_04-56-59_ryj7wz.png', 'image', 'build', 'Master Yi, build, League of Legends', 'Imagem de build atual de Master Yi, campeão do League of Legends'),
('Build_Mel', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877826/Screenshot_from_2025-07-30_05-51-57_rhrdb8.png', 'image', 'build', 'Mel, build, League of Legends', 'Imagem de build atual de Mel, campeão do League of Legends'),
('Build_Milio', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875135/Screenshot_from_2025-07-30_04-57-17_uwjip5.png', 'image', 'build', 'Milio, build, League of Legends', 'Imagem de build atual de Milio, campeão do League of Legends'),
('Build_Miss_Fortune', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875135/Screenshot_from_2025-07-30_04-57-36_tszw5v.png', 'image', 'build', 'Miss Fortune, build, League of Legends', 'Imagem de build atual de Miss Fortune, campea o do League of Legends'),
('Build_Mordekaiser', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875139/Screenshot_from_2025-07-30_04-57-53_huxwut.png', 'image', 'build', 'Mordekaiser, build, League of Legends', 'Imagem de build atual de Mordekaiser, campeão do League of Legends'),
('Build_Morgana', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875139/Screenshot_from_2025-07-30_04-58-10_o0w3yi.png', 'image', 'build', 'Morgana, build, League of Legends', 'Imagem de build atual de Morgana, campeão do League of Legends'),
('Build_Naafiri', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875140/Screenshot_from_2025-07-30_04-58-27_ubtpgu.png', 'image', 'build', 'Naafiri, build, League of Legends', 'Imagem de build atual de Naafiri, campeão do League of Legends'),
('Build_Nami', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875140/Screenshot_from_2025-07-30_04-58-44_nn1eew.png', 'image', 'build', 'Nami, build, League of Legends', 'Imagem de build atual de Nami, campeão do League of Legends'),
('Build_Nasus', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875144/Screenshot_from_2025-07-30_04-59-03_dz2wue.png', 'image', 'build', 'Nasus, build, League of Legends', 'Imagem de build atual de Nasus, campeão do League of Legends'),
('Build_Nautilus', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875144/Screenshot_from_2025-07-30_04-59-24_fxkmi5.png', 'image', 'build', 'Nautilus, build, League of Legends', 'Imagem de build atual de Nautilus, campeão do League of Legends'),
('Build_Neeko', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875145/Screenshot_from_2025-07-30_04-59-38_cyxgpl.png', 'image', 'build', 'Neeko, build, League of Legends', 'Imagem de build atual de Neeko, campeão do League of Legends'),
('Build_Nidalee', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875145/Screenshot_from_2025-07-30_04-59-54_z4bisg.png', 'image', 'build', 'Nidalee, build, League of Legends', 'Imagem de build atual de Nidalee, campeão do League of Legends'),
('Build_Nilah', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875149/Screenshot_from_2025-07-30_05-00-24_jx35yd.png', 'image', 'build', 'Nilah, build, League of Legends', 'Imagem de build atual de Nilah, campeão do League of Legends'),
('Build_Nocturne', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875150/Screenshot_from_2025-07-30_05-00-39_zhxrox.png', 'image', 'build', 'Nocturne, build, League of Legends', 'Imagem de build atual de Nocturne, campeão do League of Legends'),
('Build_Nunu', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875150/Screenshot_from_2025-07-30_05-01-08_e2sikx.png', 'image', 'build', 'Nunu, build, League of Legends', 'Imagem de build atual de Nunu, campeão do League of Legends'),
('Build_Olaf', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875150/Screenshot_from_2025-07-30_05-01-23_gygzgj.png', 'image', 'build', 'Olaf, build, League of Legends', 'Imagem de build atual de Olaf, campeão do League of Legends'),
('Build_Orianna', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875154/Screenshot_from_2025-07-30_05-01-40_mjqhby.png', 'image', 'build', 'Orianna, build, League of Legends', 'Imagem de build atual de Orianna, campeão do League of Legends'),
('Build_Ornn', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875155/Screenshot_from_2025-07-30_05-01-55_eka9wt.png', 'image', 'build', 'Ornn, build, League of Legends', 'Imagem de build atual de Ornn, campeão do League of Legends'),
('Build_Pantheon', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875155/Screenshot_from_2025-07-30_05-02-14_ixshth.png', 'image', 'build', 'Pantheon, build, League of Legends', 'Imagem de build atual de Pantheon, campeão do League of Legends'),
('Build_Poppy', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875156/Screenshot_from_2025-07-30_05-02-31_e9a3kl.png', 'image', 'build', 'Poppy, build, League of Legends', 'Imagem de build atual de Poppy, campeão do League of Legends'),
('Build_Pyke', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875158/Screenshot_from_2025-07-30_05-02-59_ocnrkt.png', 'image', 'build', 'Pyke, build, League of Legends', 'Imagem de build atual de Pyke, campeão do League of Legends'),
('Build_Qiyana', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875161/Screenshot_from_2025-07-30_05-03-35_wzszvb.png', 'image', 'build', 'Qiyana, build, League of Legends', 'Imagem de build atual de Qiyana, campeão do League of Legends'),
('Build_Quinn', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875162/Screenshot_from_2025-07-30_05-04-14_nc8owp.png', 'image', 'build', 'Quinn, build, League of Legends', 'Imagem de build atual de Quinn, campeão do League of Legends'),
('Build_Rakan', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875162/Screenshot_from_2025-07-30_05-04-28_grjnsp.png', 'image', 'build', 'Rakan, build, League of Legends', 'Imagem de build atual de Rakan, campeão do League of Legends'),
('Build_Rammus', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875163/Screenshot_from_2025-07-30_05-05-20_xhvptw.png', 'image', 'build', 'Rammus, build, League of Legends', 'Imagem de build atual de Rammus, campeão do League of Legends'),
('Build_RekSai', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875166/Screenshot_from_2025-07-30_05-05-42_dcgyki.png', 'image', 'build', 'RekSai, build, League of Legends', 'Imagem de build atual de RekSai, campeão do League of Legends'),
('Build_Rell', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875169/Screenshot_from_2025-07-30_05-06-12_e3z63x.png', 'image', 'build', 'Rell, build, League of Legends', 'Imagem de build atual de Rell, campeão do League of Legends'),
('Build_Renata', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875170/Screenshot_from_2025-07-30_05-06-39_djtsgd.png', 'image', 'build', 'Renata, build, League of Legends', 'Imagem de build atual de Renata, campeão do League of Legends'),
('Build_Renekton', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875170/Screenshot_from_2025-07-30_05-06-55_pss54m.png', 'image', 'build', 'Renekton, build, League of Legends', 'Imagem de build atual de Renekton, campeão do League of Legends'),
('Build_Rengar', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875171/Screenshot_from_2025-07-30_05-07-12_xvknvq.png', 'image', 'build', 'Rengar, build, League of Legends', 'Imagem de build atual de Rengar, campeão do League of Legends'),
('Build_Riven', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875175/Screenshot_from_2025-07-30_05-07-38_wjke3d.png', 'image', 'build', 'Riven, build, League of Legends', 'Imagem de build atual de Riven, campeão do League of Legends'),
('Build_Rumble', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875176/Screenshot_from_2025-07-30_05-07-59_l9dogk.png', 'image', 'build', 'Rumble, build, League of Legends', 'Imagem de build atual de Rumble, campeão do League of Legends'),
('Build_Ryze', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753875176/Screenshot_from_2025-07-30_05-08-18_lflxty.png', 'image', 'build', 'Ryze, build, League of Legends', 'Imagem de build atual de Ryze, campeão do League of Legends'),
('Build_Senna', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877727/Screenshot_from_2025-07-30_05-12-23_qcmohy.png', 'image', 'build', 'Senna, build, League of Legends', 'Imagem de build atual de Senna, campeão do League of Legends'),
('Build_Seraphine', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877728/Screenshot_from_2025-07-30_05-12-44_nop07b.png', 'image', 'build', 'Seraphine, build, League of Legends', 'Imagem de build atual de Seraphine, campeão do League of Legends'),
('Build_Sett', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877728/Screenshot_from_2025-07-30_05-12-58_kda7yw.png', 'image', 'build', 'Sett, build, League of Legends', 'Imagem de build atual de Sett, campeão do League of Legends'),
('Build_Shaco', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877733/Screenshot_from_2025-07-30_05-13-12_bewnui.png', 'image', 'build', 'Shaco, build, League of Legends', 'Imagem de build atual de Shaco, campeão do League of Legends'),
('Build_Shen', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877734/Screenshot_from_2025-07-30_05-35-38_spmnh3.png', 'image', 'build', 'Shen, build, League of Legends', 'Imagem de build atual de Shen, campeão do League of Legends'),
('Build_Shyvana', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877734/Screenshot_from_2025-07-30_05-36-26_hudj6k.png', 'image', 'build', 'Shyvana, build, League of Legends', 'Imagem de build atual de Shyvana, campeão do League of Legends'),
('Build_Singed', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877736/Screenshot_from_2025-07-30_05-36-43_qowsei.png', 'image', 'build', 'Singed, build, League of Legends', 'Imagem de build atual de Singed, campeão do League of Legends'),
('Build_Sion', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877740/Screenshot_from_2025-07-30_05-36-59_zaygsp.png', 'image', 'build', 'Sion, build, League of Legends', 'Imagem de build atual de Sion, campeão do League of Legends'),
('Build_Sivir', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877741/Screenshot_from_2025-07-30_05-37-14_ujgvg4.png', 'image', 'build', 'Sivir, build, League of Legends', 'Imagem de build atual de Sivir, campeão do League of Legends'),
('Build_Skarner', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877741/Screenshot_from_2025-07-30_05-37-27_hnd3ro.png', 'image', 'build', 'Skarner, build, League of Legends', 'Imagem de build atual de Skarner, campeão do League of Legends'),
('Build_Smolder', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877830/Screenshot_from_2025-07-30_05-52-21_tvyxhj.png', 'image', 'build', 'Smolder, build, League of Legends', 'Imagem de build atual de Smolder, campeão do League of Legends'),
('Build_Sona', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877743/Screenshot_from_2025-07-30_05-37-54_nlemfr.png', 'image', 'build', 'Sona, build, League of Legends', 'Imagem de build atual de Sona, campeão do League of Legends'),
('Build_Soraka', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877747/Screenshot_from_2025-07-30_05-38-15_hji8ua.png', 'image', 'build', 'Soraka, build, League of Legends', 'Imagem de build atual de Soraka, campeão do League of Legends'),
('Build_Swain', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877747/Screenshot_from_2025-07-30_05-38-29_uzqmcl.png', 'image', 'build', 'Swain, build, League of Legends', 'Imagem de build atual de Swain, campeão do League of Legends'),
('Build_Sylas', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877748/Screenshot_from_2025-07-30_05-38-46_ayrwvv.png', 'image', 'build', 'Sylas, build, League of Legends', 'Imagem de build atual de Sylas, campeão do League of Legends'),
('Build_Syndra', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877748/Screenshot_from_2025-07-30_05-39-01_gmiyue.png', 'image', 'build', 'Syndra, build, League of Legends', 'Imagem de build atual de Syndra, campeão do League of Legends'),
('Build_TK', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877753/Screenshot_from_2025-07-30_05-39-21_wa2gez.png', 'image', 'build', 'TK, build, League of Legends', 'Imagem de build atual de TK, campeão do League of Legends'),
('Build_Taliyah', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877754/Screenshot_from_2025-07-30_05-40-05_tixxcz.png', 'image', 'build', 'Taliyah, build, League of Legends', 'Imagem de build atual de Taliyah, campeão do League of Legends'),
('Build_Talon', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877754/Screenshot_from_2025-07-30_05-40-23_vrmh0w.png', 'image', 'build', 'Talon, build, League of Legends', 'Imagem de build atual de Talon, campeão do League of Legends'),
('Build_Taric', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877755/Screenshot_from_2025-07-30_05-40-37_dsgv5s.png', 'image', 'build', 'Taric, build, League of Legends', 'Imagem de build atual de Taric, campeão do League of Legends'),
('Build_Teemo', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877760/Screenshot_from_2025-07-30_05-40-59_knerer.png', 'image', 'build', 'Teemo, build, League of Legends', 'Imagem de build atual de Teemo, campeão do League of Legends'),
('Build_Thresh', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877761/Screenshot_from_2025-07-30_05-41-18_ujmyvw.png', 'image', 'build', 'Thresh, build, League of Legends', 'Imagem de build atual de Thresh, campeão do League of Legends'),
('Build_Tristana', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877761/Screenshot_from_2025-07-30_05-41-37_xojk5c.png', 'image', 'build', 'Tristana, build, League of Legends', 'Imagem de build atual de Tristana, campeão do League of Legends'),
('Build_Trundle', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877762/Screenshot_from_2025-07-30_05-41-56_orvwfn.png', 'image', 'build', 'Trundle, build, League of Legends', 'Imagem de build atual de Trundle, campeão do League of Legends'),
('Build_Tryndamere', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877767/Screenshot_from_2025-07-30_05-42-20_uvqkwt.png', 'image', 'build', 'Tryndamere, build, League of Legends', 'Imagem de build atual de Tryndamere, campeão do League of Legends'),
('Build_Twisted_Fate', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877767/Screenshot_from_2025-07-30_05-42-37_nfdejy.png', 'image', 'build', 'Twisted Fate, build, League of Legends', 'Imagem de build atual de Twisted Fate, campeão do League of Legends'),
('Build_Twitch', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877768/Screenshot_from_2025-07-30_05-42-55_n1xyey.png', 'image', 'build', 'Twitch, build, League of Legends', 'Imagem de build atual de Twitch, campeão do League of Legends'),
('Build_Udyr', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877769/Screenshot_from_2025-07-30_05-43-11_rwb10t.png', 'image', 'build', 'Udyr, build, League of Legends', 'Imagem de build atual de Udyr, campeão do League of Legends'),
('Build_Urgot', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877774/Screenshot_from_2025-07-30_05-43-25_onhxxn.png', 'image', 'build', 'Urgot, build, League of Legends', 'Imagem de build atual de Urgot, campeão do League of Legends'),
('Build_Varus', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877775/Screenshot_from_2025-07-30_05-43-52_ssmiij.png', 'image', 'build', 'Varus, build, League of Legends', 'Imagem de build atual de Varus, campeão do League of Legends'),
('Build_Vayne', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877775/Screenshot_from_2025-07-30_05-44-13_kypwoy.png', 'image', 'build', 'Vayne, build, League of Legends', 'Imagem de build atual de Vayne, campeão do League of Legends'),
('Build_Veigar', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877777/Screenshot_from_2025-07-30_05-44-29_yhontc.png', 'image', 'build', 'Veigar, build, League of Legends', 'Imagem de build atual de Veigar, campeão do League of Legends'),
('Build_Velkoz', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877781/Screenshot_from_2025-07-30_05-44-47_zupmsv.png', 'image', 'build', 'Velkoz, build, League of Legends', 'Imagem de build atual de Velkoz, campeão do League of Legends'),
('Build_Vex', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877782/Screenshot_from_2025-07-30_05-45-04_yquejk.png', 'image', 'build', 'Vex, build, League of Legends', 'Imagem de build atual de Vex, campeão do League of Legends'),
('Build_Vi', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877782/Screenshot_from_2025-07-30_05-45-18_a6lb2a.png', 'image', 'build', 'Vi, build, League of Legends', 'Imagem de build atual de Vi, campeão do League of Legends'),
('Build_Viego', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877784/Screenshot_from_2025-07-30_05-45-40_lu4c1f.png', 'image', 'build', 'Viego, build, League of Legends', 'Imagem de build atual de Viego, campeão do League of Legends'),
('Build_Viktor', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877786/Screenshot_from_2025-07-30_05-45-59_x7jktg.png', 'image', 'build', 'Viktor, build, League of Legends', 'Imagem de build atual de Viktor, campeão do League of Legends'),
('Build_Vladimir', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877790/Screenshot_from_2025-07-30_05-46-18_hpbp9p.png', 'image', 'build', 'Vladimir, build, League of Legends', 'Imagem de build atual de Vladimir, campeão do League of Legends'),
('Build_Volibear', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877790/Screenshot_from_2025-07-30_05-46-36_gkm9dr.png', 'image', 'build', 'Volibear, build, League of Legends', 'Imagem de build atual de Volibear, campeão do League of Legends'),
('Build_Warwick', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877791/Screenshot_from_2025-07-30_05-46-56_kfeqgb.png', 'image', 'build', 'Warwick, build, League of Legends', 'Imagem de build atual de Warwick, campeão do League of Legends'),
('Build_Wukong', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877794/Screenshot_from_2025-07-30_05-47-15_ql9xwe.png', 'image', 'build', 'Wukong, build, League of Legends', 'Imagem de build atual de Wukong, campeão do League of Legends'),
('Build_Xayah', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877800/Screenshot_from_2025-07-30_05-47-41_t4eni0.png', 'image', 'build', 'Xayah, build, League of Legends', 'Imagem de build atual de Xayah, campeão do League of Legends'),
('Build_Xerath', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877801/Screenshot_from_2025-07-30_05-47-56_w1b7ox.png', 'image', 'build', 'Xerath, build, League of Legends', 'Imagem de build atual de Xerath, campeão do League of Legends'),
('Build_Xin_Zhao', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877801/Screenshot_from_2025-07-30_05-48-13_owkd2w.png', 'image', 'build', 'Xin Zhao, build, League of Legends', 'Imagem de build atual de Xin Zhao, campeão do League of Legends'),
('Build_Yasuo', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877804/Screenshot_from_2025-07-30_05-48-44_rzcjog.png', 'image', 'build', 'Yasuo, build, League of Legends', 'Imagem de build atual de Yasuo, campeão do League of Legends'),
('Build_Yone', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877808/Screenshot_from_2025-07-30_05-49-19_thno38.png', 'image', 'build', 'Yone, build, League of Legends', 'Imagem de build atual de Yone, campeão do League of Legends'),
('Build_Yorick', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877809/Screenshot_from_2025-07-30_05-49-35_yxk1b4.png', 'image', 'build', 'Yorick, build, League of Legends', 'Imagem de build atual de Yorick, campeão do League of Legends'),
('Build_Yuumi', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877809/Screenshot_from_2025-07-30_05-49-51_asxqjl.png', 'image', 'build', 'Yuumi, build, League of Legends', 'Imagem de build atual de Yuumi, campeão do League of Legends'),
('Build_Zac', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877810/Screenshot_from_2025-07-30_05-50-06_sbggax.png', 'image', 'build', 'Zac, build, League of Legends', 'Imagem de build atual de Zac, campeão do League of Legends'),
('Build_Zed', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877812/Screenshot_from_2025-07-30_05-50-19_dkwal6.png', 'image', 'build', 'Zed, build, League of Legends', 'Imagem de build atual de Zed, campeão do League of Legends'),
('Build_Zeri', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877815/Screenshot_from_2025-07-30_05-50-43_sf1a3h.png', 'image', 'build', 'Zeri, build, League of Legends', 'Imagem de build atual de Zeri, campeão do League of Legends'),
('Build_Ziggs', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877819/Screenshot_from_2025-07-30_05-50-57_r5avtt.png', 'image', 'build', 'Ziggs, build, League of Legends', 'Imagem de build atual de Ziggs, campeão do League of Legends'),
('Build_Zilean', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877820/Screenshot_from_2025-07-30_05-51-15_lxo6za.png', 'image', 'build', 'Zilean, build, League of Legends', 'Imagem de build atual de Zilean, campeão do League of Legends'),
('Build_Zoe', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877825/Screenshot_from_2025-07-30_05-51-30_g9mhvl.png', 'image', 'build', 'Zoe, build, League of Legends', 'Imagem de build atual de Zoe, campeão do League of Legends'),
('Build_Zyra', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877825/Screenshot_from_2025-07-30_05-51-46_d9dbfo.png', 'image', 'build', 'Zyra, build, League of Legends', 'Imagem de build atual de Zyra, campeão do League of Legends'),
('Build_Smolder', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877830/Screenshot_from_2025-07-30_05-52-21_tvyxhj.png', 'image', 'build', 'Smolder, build, League of Legends', 'Imagem de build atual de Smolder, campeão do League of Legends'),
('Build_Yunara', 'https://res.cloudinary.com/dbazprstl/image/upload/v1753877834/Screenshot_from_2025-07-30_05-52-47_yqllr3.png', 'image', 'build', 'Yunara, build, League of Legends', 'Imagem de build atual de Yunara, campeão do League of Legends');

INSERT INTO media_files (file_name, file_url, file_type, category, tags)
VALUES 
('GIF_bomDia','https://res.cloudinary.com/dbazprstl/image/upload/v1743592512/GIF_bomDia.webp','gif','bom dia','dog,bom dia,gif'),
('GIF_bomDia2','https://res.cloudinary.com/dbazprstl/image/upload/v1757256725/bomdia21_kq1t5i.webp','gif','bom dia','dog2,bom dia,gif'),
('GIF_Corinthians', 'https://res.cloudinary.com/dbazprstl/image/upload/v1758494598/Corinthians_ocphzl.gif', 'gif', 'futebol', 'Corinthians, futebol, gif'),
('GIF_Palmeiras', 'https://res.cloudinary.com/dbazprstl/image/upload/v1758494598/pameiras_p2pljd.gif', 'gif', 'futebol', 'Palmeiras, futebol, gif'),
('GIF_Santos', 'https://res.cloudinary.com/dbazprstl/image/upload/v1758494597/Santos_lij5nq.gif', 'gif', 'futebol', 'Santos, futebol, gif'),
('GIF_Flamengo', 'https://res.cloudinary.com/dbazprstl/image/upload/v1758494597/Flamengo_ntc4ou.gif', 'gif', 'futebol', 'Flamengo, futebol, gif'),
('GIF_SaoPaulo', 'https://res.cloudinary.com/dbazprstl/image/upload/v1758494598/S%C3%A3o_paulo_dljirx.gif', 'gif', 'futebol', 'São Paulo, futebol, gif'),
('GIF_NikolasL', 'https://res.cloudinary.com/dbazprstl/image/upload/v1758494606/nikolas_L_jtuccr.gif', 'gif', 'meme', 'Nikolas, L, meme, gif'),
('GIF_MarioL', 'https://res.cloudinary.com/dbazprstl/image/upload/v1758494598/L_oooqzg.gif', 'gif', 'meme', 'Mario, L, meme, gif'),
('GIF_OLobo', 'https://res.cloudinary.com/dbazprstl/image/upload/v1758494600/O_lobo_aaxerp.gif', 'gif', 'meme', 'Lobo, meme, gif'),
('GIF_Bolsonaro', 'https://res.cloudinary.com/dbazprstl/image/upload/v1758494600/bolsonaro_m58u9a.gif', 'gif', 'meme', 'Bolsonaro, meme, gif'),
('GIF_Lula', 'https://res.cloudinary.com/dbazprstl/image/upload/v1758494598/lula_gzmv55.gif', 'gif', 'meme', 'Lula, meme, gif'),
('GIF_Gap', 'https://res.cloudinary.com/dbazprstl/image/upload/v1758494913/Gap_bwnq3j.gif', 'gif', 'meme', 'Gap, meme, gif');


